# -*- coding: utf-8 -*-
from pathlib import Path
r=Path(__file__).resolve().parents[1]/'03_Cabinets/CB001_Curiosity_Low_Maple_Walnut/models/D16'
p=r/'CB001_D16_viewer.html';s=p.read_text(encoding='utf8')
s=s.replace('<label><input id="exploded" type="checkbox">展開部件</label>','')
s=s.replace('<h2>模型爆炸圖</h2>','''<h2>模型爆炸圖 · 分組檢視</h2><p>把手共 <b>2 組</b>（H01／H02），每組含橢圓頭、接頸、底座 3 個模型分件。</p><p><select id="groupFilter" aria-label="GROUP 分組"></select></p><p><select id="subFilter" aria-label="細部分組"></select></p><div class="explode-controls"><label><input id="partLabels" type="checkbox" checked>顯示編號</label> <label><input id="spreadParts" type="checkbox">分件攤開</label><label><input id="exploded" type="checkbox">展開部件</label></div><p id="groupCount"></p><div id="groupParts"></div>''')
s=s.replace('CSV</a><small>','CSV</a> · <a href="gallery/verification.html" target="_blank">尺寸與數量驗證</a><small>')
s=s.replace('</style>','''aside{box-sizing:border-box;min-width:0}aside p{margin:10px 0;line-height:1.5}.explode-controls{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.explode-controls label{display:inline-flex;align-items:center;gap:6px;box-sizing:border-box;min-height:40px;line-height:1.4;margin:0;white-space:nowrap}.explode-controls input{margin:0;flex:none}#groupParts{margin:10px 0 14px}#explodeAmount{display:block;width:100%;box-sizing:border-box;margin:12px 0}#groupFilter,#subFilter,#partlist{box-sizing:border-box;max-width:100%}#groupFilter,#subFilter{width:100%;padding:8px}#groupParts{display:flex;flex-wrap:wrap;gap:4px;max-height:140px;overflow:auto}#groupParts button{padding:4px;font-size:12px}.partTag{position:absolute;background:#fffbea;border:1px solid #8f795b;border-radius:4px;padding:2px 4px;font:11px system-ui;pointer-events:auto;cursor:pointer}#partOverlay{position:absolute;inset:0;pointer-events:none;overflow:hidden}#groupCount{font-size:13px}</style>''')
js=r'''
const gf=document.getElementById('groupFilter'),sf=document.getElementById('subFilter');
gf.add(new Option('全部 GROUP',''));[...new Set(partRows.map(p=>p.group))].forEach(g=>gf.add(new Option(g,g)));
const overlay=document.createElement('div');overlay.id='partOverlay';root.appendChild(overlay);
const tags=objects.map((o,i)=>{const t=document.createElement('button');t.className='partTag';t.textContent=partRows[i].id;t.title=partRows[i].component;t.onclick=()=>choose(i);overlay.appendChild(t);return t;});
function matches(i){return (!gf.value||partRows[i].group===gf.value)&&(!sf.value||partRows[i].subgroup===sf.value);}
function visibleParts(){objects.forEach((o,i)=>o.visible=matches(i)&&(o.userData.kind!=='GLASS'||document.getElementById('glass').checked)&&(!o.name.startsWith('BACK')||document.getElementById('back').checked));}
function fitGroup(){const b=new THREE.Box3();objects.filter(o=>o.visible).forEach(o=>b.union(new THREE.Box3().setFromObject(o)));if(b.isEmpty())return;const c=b.getCenter(new THREE.Vector3()),radius=b.getSize(new THREE.Vector3()).length()/2;const angle=Math.min(camera.fov*Math.PI/360,Math.atan(Math.tan(camera.fov*Math.PI/360)*camera.aspect));const dist=Math.max(.12,radius/Math.sin(angle)*1.18);view(c.clone().add(new THREE.Vector3(-1,-1.8,.65).normalize().multiplyScalar(dist)).toArray(),c.toArray());}
function arrange(){explode();if(document.getElementById('spreadParts').checked){const list=objects.map((o,i)=>({o,i})).filter(({i})=>matches(i));const boxes=list.map(({o})=>new THREE.Box3().setFromBufferAttribute(o.geometry.attributes.position));const maxW=Math.max(.08,...boxes.map(b=>b.max.x-b.min.x))+.08,maxH=Math.max(.08,...boxes.map(b=>b.max.z-b.min.z))+.08;const cols=Math.ceil(Math.sqrt(list.length));list.forEach(({o},k)=>{const c=boxes[k].getCenter(new THREE.Vector3());o.position.set((k%cols)*maxW-c.x,-c.y,-Math.floor(k/cols)*maxH-c.z);});}visibleParts();}
function fillParts(){sel.innerHTML='';sel.add(new Option('全部部件','-1'));const list=partRows.map((p,i)=>({p,i})).filter(({i})=>matches(i));list.forEach(({p,i})=>sel.add(new Option(p.id+' · '+p.material+' · '+p.component,i)));const host=document.getElementById('groupParts');host.innerHTML='';list.forEach(({p,i})=>{const b=document.createElement('button');b.textContent=p.id;b.title=p.component;b.onclick=()=>choose(i);host.appendChild(b);});document.getElementById('groupCount').textContent='目前 '+list.length+' 個模型分件／全櫃 99 個；不是採購件數。';choose(-1);}
function changeGroup(){sf.innerHTML='';sf.add(new Option('全部細部分組',''));[...new Set(partRows.filter(p=>!gf.value||p.group===gf.value).map(p=>p.subgroup))].forEach(g=>sf.add(new Option(g,g)));changeSub();}
function changeSub(){fillParts();arrange();fitGroup();}
gf.onchange=changeGroup;sf.onchange=changeSub;document.getElementById('spreadParts').onchange=()=>{arrange();fitGroup();};document.getElementById('exploded').onchange=()=>{arrange();fitGroup();};document.getElementById('explodeAmount').oninput=arrange;document.getElementById('glass').onchange=visibleParts;document.getElementById('back').onchange=visibleParts;
function drawTags(){if(gf.value||document.getElementById("spreadParts").checked)grid.visible=false;const used=[];objects.forEach((o,i)=>{const t=tags[i];t.style.display='none';if(!o.visible||!document.getElementById('partLabels').checked)return;if(!gf.value&&!sf.value&&sel.value!==String(i))return;const c=new THREE.Box3().setFromObject(o).getCenter(new THREE.Vector3()).project(camera);if(c.z< -1||c.z>1)return;let x=(c.x+1)*root.clientWidth/2,y=(1-c.y)*root.clientHeight/2;while(used.some(a=>Math.abs(a[0]-x)<44&&Math.abs(a[1]-y)<21))y+=22;used.push([x,y]);t.style.display='block';t.style.left=Math.max(0,Math.min(root.clientWidth-48,x))+'px';t.style.top=Math.max(0,Math.min(root.clientHeight-22,y))+'px';});}
sf.add(new Option('全部細部分組',''));[...new Set(partRows.map(p=>p.subgroup))].forEach(g=>sf.add(new Option(g,g)));fillParts();
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);drawTags();});
'''
s=s.replace('</script></body>',js+'</script></body>');p.write_text(s,encoding='utf8')
